### ISSUE TITLE
Support for earlier versions of macOS

### ISSUE THREAD

**Issue by jamsilva** [steventheworker/DockAltTab#1]
DockAltTab is compiled for macOS >= 11.3 but AltTab itself supports macOS from 10.12.
Can you provide builds for any versions earlier than 11 as well?

**Comment by steventheworker** [comment]
Added it to the website and GitHub release, does this work?
https://github.com/steventheworker/DockAltTab/releases/download/v1.2/DockAltTab-maOS10.12.zip

I'll provide the same build target for future builds int he releases section and add it to the changelog.
https://dockalttab.netlify.app/changelog/

**Comment by jamsilva** [comment]
It works for me (it's not very consistent, sometimes clicking a dock icon doesn't bring up the AltTab thumbnails). I had to change the shortcut in AltTab though, because of this: https://alt-tab-macos.netlify.app/contributing - "Keyboards from other countries have different layout which impact shortcuts
e.g. the default ⌥` shortcut should become ⌥< on a Spanish ISO keyboard"

**Comment by steventheworker** [comment]
v2.0 will be out shortly and will no longer trigger keys, but you will have to uninstall AltTab and replace it with one you can download from our releases here / on https://dockalttab.netlify.app
