### ISSUE TITLE
UI - Adjustable Spacing: padding & margin sliders

### ISSUE THREAD

**Issue by sdburrows** [steventheworker/DockAltTab#10]
Is there anyway we could adjust the preview window border? It is quite thick. I think the UI follows the AltTab, but there is no option to change that. Perhaps, DockAltTab can create a config different to AltTab?

**Comment by steventheworker** [comment]
I opted to just remove all padding for DockAltTab previews only, except for a 1px border. A lot better this way, but maybe I'm missing something, and I haven't made my mind up if I want to make it customizable, so I changed the title.

**Comment by steventheworker** [comment]
I couldn't think of a use case where re-adding the border is useful (bar aesthetics)
