### ISSUE TITLE
Menubar icon bug

### ISSUE THREAD

**Issue by sdburrows** [steventheworker/DockAltTab#12]
Steps to reproduce:

1. Run DockAltTab
2. Disable  "Add icon to menu bar"
3. Restart app either by quitting in Activity Monitor or restarting computer
4. DockAltTab icon reappears in menubar

Expected behaviour is menubar icon should remain hidden but on show the app itself when launch again from Applications folder / Spotlight / launchpad.

**Comment by steventheworker** [comment]
Yeah this is to prevent blocking oneself from the preferences window, since I haven't figured out how to bring it up w/o the dock icon (eg: via spotlight).

This will definitely be fixed... but more quickly if shown support through replies / thumbs ups.

**Comment by steventheworker** [comment]
Fixed in v2.91.0
