### ISSUE TITLE
Preview image not centered

### ISSUE THREAD

**Issue by Moolynx** [steventheworker/DockAltTab#13]
I noticed the preview image is not centered above the dock icon and the border is overlapping the dock. Is there any option to adjust this? Thanks. 
![Screenshot 2022-12-17 at 20 04 58](https://user-images.githubusercontent.com/120015936/208234728-4382e239-6bcf-45a1-92ad-d56f0f8228ed.png)
![Screenshot 2022-12-17 at 20 05 03](https://user-images.githubusercontent.com/120015936/208234731-3a0eca10-675c-4845-8861-c107755082e1.png)

**Comment by steventheworker** [comment]
Currently previews are set to go to mouse.x coordinate - 2 dock icon widths. This'll probably addressed in the same update that stops clipping previews at the end of the monitor width (>= 3 previews on dock icons closer to the end of the screen cause this) &nbsp; which I consider more important.

**Comment by steventheworker** [comment]
I actually decided to fix the centering before the clipping after all. Update to v2.8 and to the latest scriptable AltTab and it will work 👍

**Comment by steventheworker** [comment]
I actually decided to fix the centering before the clipping after all. Update to v2.7 and to the latest scriptable AltTab and it will work 👍

**Comment by steventheworker** [comment]
I actually decided to fix the centering before the clipping after all. Update to v2.8 and to the latest scriptable AltTab and it will work 👍
