### ISSUE TITLE
Pull request for README.md - Fix for damaged app error

### ISSUE THREAD

**Issue by barrrricade** [steventheworker/DockAltTab#15]
Hey dude,
Like your app. Accidentally updated the modded AltTab then dockalttab stopped working.
Reinstalled and troubleshoot but modded AltTab error showed `AltTab is damaged and can’t be opened. You should move it to the Trash`

Can add to README.md:
Error:
When opening modded alttab
`AltTab is damaged and can’t be opened. You should move it to the Trash`

Cause: signing failed.

Fix: Disable Gatekeeper 
Steps:
Global disable (not recommended):
`sudo spctl --master-disable` 

or

Disabling Gatekeeper for one application only: (note: path to modded alttab app)
`xattr -dr com.apple.quarantine /Applications/AltTab.app`

**Comment by steventheworker** [comment]
I was pushing debug builds not knowing it would make bypassing gatekeeper even harder... 😳

It doesn't say it's damaged anymore though, and bypassing is a lot easier, now that I'm pushing release builds again.
