### ISSUE TITLE
Problem with supported AltTab

### ISSUE THREAD

**Issue by SecrestTheStudent** [steventheworker/DockAltTab#16]
The most recent two versions don't launch. They give the error message that the application must be damaged and to move it to the trash. The version that DockAltTab directs me to download (the one from September 16th by the looks of it) does launch.

![image](https://user-images.githubusercontent.com/67644036/220306061-722592f3-ca11-410e-8c2a-909ad3da8df3.png)

**Comment by Moolynx** [comment]
@steventheworker, has there been any update to this? Mine broke too when updated to the later version of AltTab.

**Comment by steventheworker** [comment]
My laptop got wet 21 hours ago and I was about to push an update... give me 3 hours (and then some to finish...), and hopefully I'll have it ready in <12 hours 😅.

**Comment by Moolynx** [comment]
Sorry to hear your laptop got wet. But it's wonderful, we finally get an update! Look forward to bug free update 👯

**Comment by Moolynx** [comment]
@steventheworker, thanks for releasing v2.7 but the download link doesn't work :( 

https://github.com/steventheworker/DockAltTab/releases/download/v2.7/DockAltTab-v2.7.zip

**Comment by steventheworker** [comment]
Try the link again please, should be up now!

Also, currently in the middle of fixing some conflicts updating AltTab to v6.55.0, so I'm going to reupload v6.52.1 (the one this issue says is damaged), will post the link for that very soon.

**Comment by Moolynx** [comment]
Thanks for the speedy response. I might wait a few hours then to get the full set. Thanks! :)

**Comment by steventheworker** [comment]
@SecrestTheStudent I looked into this and it says the app is "damaged" because the apps aren't notarized (due to not renewing my $100 apple developer license), however, you can get it work by bypassing gatekeeper in one of two ways:
1.  run ```xattr -dr com.apple.quarantine /Applications/AltTab.app``` in terminal
2. OR... After getting the damaged error, open System Preferences. then go to Security&Privacy tab. Click the lock at the bottom to make changes. Enter your password. Then allow AltTab. It should now run.

**Comment by steventheworker** [comment]
The AltTab mod is now updated, sorry for the delay, am seriously distracted by that single tapping bug.

**Comment by SecrestTheStudent** [comment]
Thanks for being so quick with the responses and sorry for being so slow to get back. I was able to use the bypassing on the gatekeeper and after some fiddling with the accessibility/screen recording whatnots I seem to be good. Really love your program. It's exactly what I was looking for.
