### ISSUE TITLE
Window previews cut off on far right dock applications

### ISSUE THREAD

**Issue by ftorelli165** [steventheworker/DockAltTab#18]
I have run into this situation several times now where if I hover over an application at the end of the dock that have multiple documents open it will either cut these off or not show all of them. See attached photo. In the attached photo it is only showing part of 2 documents, however I have 3 minimized for this application.
<img width="213" alt="Screenshot at Apr 14 11-51-19" src="https://user-images.githubusercontent.com/88461866/232093251-37022c60-6c0f-4862-b839-60b62f8adc73.png">

**Comment by steventheworker** [comment]
Related to issues #10 and #13.

Ideally I'd like to shrink the previews to a certain point, then rely on the grey area to horizontally scroll the rest.

**Comment by steventheworker** [comment]
The latest scriptable AltTab (1.92.0) has this fixed!

**Comment by shredthaGNAR** [comment]
Looks great and works for both sizes...now if we get that pesky rounding border radius cuttoff problem when in MacOS mode, they have curved edges instead of 90 degrees like Windows-we would really be rocking! Getting close! good work fixing problem and now fiinder windows etc no longer cutoff on ends of screen etc looks good!

**Comment by steventheworker** [comment]
@shredthaGNAR 
> Looks great and works for both sides...now if we get that pesky rounding border radius cuttoff problem when in MacOS mode, they have curved edges instead of 90 degrees like Windows-we would really be rocking! Getting close! good work fixing problem and now fiinder windows etc no longer cutoff on ends of screen etc looks good!

The latest scriptable AltTab update fixes this, finally.
