### ISSUE TITLE
Unable to select window previews due to auttoclick/select

### ISSUE THREAD

**Issue by WynStaXxx** [steventheworker/DockAltTab#19]
Was woking great. Updated to MacOS Beta 13.4 and now(?) I am unable to select a window, it auto selects the 1st window preview. Seems like auto click. As soon as I hover over previews it autooslects the 1stt one. Also have multiple actions I created in BTT are acting strange/not working example had a option-click two finger tap to auto hide other apps, not working so disabled. Tried all all obvious troubleshoots but no effect 

FYI posted on discord re:feature request. I have created trackpad shortcuts via applescript and BTT to move around back and forth previews and minimize/unminimize/hide/hide others/select without needing to use keyboard. Obviously unable to use them now  😆  but maybe someething to add later. 

If you need any help let me know. Thanks for great app

**Comment by steventheworker** [comment]
Sometimes a permission stops applying and may even linger after running the command to remove all permissions:
 ```tccutil reset All com.steventheworker.DockAltTab```
After running this, check for any permissions that linger (Input Monitoring, Accessibility, Automation, Screen Recording), and manually remove them.

After doing that, close settings, and then open DockAltTab and reapply/reinstall all the permissions.

**Comment by WynStaXxx** [comment]
fixed btw. thanks! went away and I should have removed this. No need to be on the bug list anymore unless someone finds your instructions helpful, which they are. So maybe stay for that reason, but no bug ;)
