### ISSUE TITLE
White Selection Hover Border Around Window Previews Corners Cut-off

### ISSUE THREAD

**Issue by shredthaGNAR** [steventheworker/DockAltTab#22]
White border around Window Previews corners are cut-off on the edges-the left side and the right side when >1+ previews. Not ALL corners looks just like far edges...guessing has something to do with the border radius ;) reminds me of a partticular CSS styling issue/quirk
<img width="952" alt="Screenshot 2023-05-08 at 12 13 24 AM" src="https://user-images.githubusercontent.com/37919512/236759606-f2305bee-fc1a-478d-b766-ac90bfd5484d.png">
<img width="568" alt="Screenshot 2023-05-08 at 12 18 59 AM" src="https://user-images.githubusercontent.com/37919512/236760946-9136af07-b9ea-418d-afc0-230cb9db7850.png">

**Comment by steventheworker** [comment]
Ah it seems the changes I made to the padding/border look wonkier on the "macOS" theme. 

You can change this in AltTab preferences -> Appearance -> Theme, and set it to "Windows" until I push an update fixing the "macOS" theme.

**Comment by steventheworker** [comment]
It's been patched to fix the white border part of the issue, will patch v1.7 a final time to close the issue. Just need to fix the preview corner part...

**Comment by steventheworker** [comment]
Fixed in scriptable AltTab 1.93.0
