### ISSUE TITLE
Make the "red box" closeable

### ISSUE THREAD

**Issue by gxgl** [steventheworker/DockAltTab#24]
Hello,

nice work!!!
Can you make the "red box" - message about the AltTab, closeable? :)

![red_box](https://github.com/steventheworker/DockAltTab/assets/11505258/e91432ca-195b-4a34-9182-1e01d7b7704f)

Thanks a lot!

All the best,
George

**Comment by steventheworker** [comment]
It closes itself now... hopefully it's not more annoying this way as it's always on top until DAT sees AltTab's running.
