### ISSUE TITLE
Uninstall the custom AltTab branch and reinstall the AltTab, which will be booted up twice upon startup.

### ISSUE THREAD

**Issue by vhvy** [steventheworker/DockAltTab#5]
```
cd ~/Library/LaunchAgents
```

`com.lwouis.alt-tab-macos.plist` and `com.steventheworker.alt-tab-macos.plist` is same login item, it cause the AltTab to boot twice.

**Comment by steventheworker** [comment]
You should uninstall the other copy (by putting it in the trash and emptying it). It can sometimes confuse spotlight, or DockAltTab may relaunch the wrong version if AltTab ever crashes.
